version: '3'
services:
 app:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: gohappyclubapp
   ports:
     - '8081:8081'
   volumes:
     - ./app:/app
     - /dev:/dev
     - /tmp:/tmp
     - /var/run/docker.sock:/var/run/docker.sock
   environment:
     - ADB_SERVER_PORT=5037
     - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
   networks:
     - app-network
networks:
 app-network:
   driver: bridge